name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  deploy-api-service-course:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          # script: 'cd /home/cowik/prod/microservice-project/api-service-course && ./deploy.sh'
          script: |
            cd /home/cowik/prod/microservice-project/api-service-course
            composer install
            ./env-generator-prod.sh
            php artisan key:generate
            sudo chown -R www-data.www-data /home/cowik/prod/microservice-project/api-service-course
            sudo chmod -R 755 /home/cowik/prod/microservice-project/api-service-course
            sudo chmod -R 777 /home/cowik/prod/microservice-project/api-service-course/storage
            sudo chmod 777 deploy.sh
            ./deploy.sh